# Generated by Django 3.0.5 on 2020-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=5000)),
                ('phone_number', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('edit_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
