# Generated by Django 3.1.3 on 2020-11-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201113_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice_post',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='result_post',
            old_name='create_date',
            new_name='create_at',
        ),
    ]
