# Generated by Django 2.2.4 on 2020-11-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201120_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_post',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='image_9',
        ),
        migrations.AddField(
            model_name='notice_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
