# Generated by Django 2.2.4 on 2020-11-20 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201120_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_post',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_post',
            name='business_finish_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result_post',
            name='business_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_post',
            name='business_start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result_post',
            name='clicks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='result_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='result_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='result_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='result_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='result_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
