# Generated by Django 2.2.4 on 2020-11-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201120_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result_post',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='result_post',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='result_post',
            name='edit_at',
        ),
        migrations.RemoveField(
            model_name='result_post',
            name='title',
        ),
    ]
