# Generated by Django 2.2.4 on 2020-11-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201120_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_post',
            name='edit_at',
        ),
        migrations.RemoveField(
            model_name='notice_post',
            name='edit_at',
        ),
    ]
