# Generated by Django 2.2.4 on 2020-11-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20201124_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_post',
            name='clicks',
            field=models.IntegerField(default=1),
        ),
    ]
