# Generated by Django 2.2.4 on 2020-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_information_post_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='information_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='information_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='information_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='information_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
