# Generated by Django 3.1.4 on 2020-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20201125_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_post',
            options={'verbose_name': '문의글', 'verbose_name_plural': '문의글'},
        ),
        migrations.AlterModelOptions(
            name='notice_post',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AlterModelOptions(
            name='result_post',
            options={'verbose_name': '공사실적', 'verbose_name_plural': '공사실적'},
        ),
        migrations.AlterField(
            model_name='information_post',
            name='author',
            field=models.CharField(max_length=50, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='clicks',
            field=models.IntegerField(default=1, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='password',
            field=models.CharField(max_length=50, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='information_post',
            name='title',
            field=models.CharField(max_length=500, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='clicks',
            field=models.IntegerField(default=1, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='address',
            field=models.CharField(max_length=200, verbose_name='공사주소'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='business_finish_at',
            field=models.DateField(blank=True, null=True, verbose_name='공사마감일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='공사이름'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='business_start_at',
            field=models.DateField(blank=True, null=True, verbose_name='공사시작일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='공사내용'),
        ),
    ]
