# Generated by Django 3.1.4 on 2020-12-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20201204_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_post',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='result_post',
            name='file_5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
