# Generated by Django 2.2.4 on 2020-12-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20201204_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_post',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='information_post',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='information_post',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='information_post',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='information_post',
            name='file_5',
        ),
    ]
